spring:
  application:
    name: broker

server:
  port: 8853

eureka:
  client:
    service-url:
      defaultZone: http://chess-eureka:8761/eureka/
# logging:
#   file:
#     name: broker.log
#   pattern:
#     console: 