spring :
  application:
    name : gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders : "*"

server :
  port : 9003

eureka :
  client :
    serviceUrl :
      defaultZone : http://chess-eureka:8761/eureka