spring:
  application:
    name: authservice

  datasource:
    url: jdbc:mysql://localhost:3306/chess?useSSL=false&serverTimezone=UTC
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform : org.hibernate.dialect.MySQLDialect

eureka :
  client :
    serviceUrl :
      defaultZone : http://localhost:8761/eureka/

server:
  port: 9001

